version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: make test
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/blog
    expose:
      - "8080"

  db:
    image: postgres:15
    container_name: js-fastify-blog-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: