version: "3.9"

services:
  app:
    image: ilovemakonnen/devops-for-developers-project-74
    container_name: js-fastify-blog-app
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgres://postgres:password@db:5432/blog"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: js-fastify-blog-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: